const Words = [
  {
    id: 1,
    word: 'apple',
    letter_5: ['appel', 'apple', 'pepla'],
    letter_4: ['leap', 'pale', 'palp', 'peal', 'plea'],
    letter_3: [
      'ale',
      'alp',
      'ape',
      'app',
      'lap',
      'lea',
      'pal',
      'pap',
      'pea',
      'pep',
    ],
  },
  {
    id: 2,
    word: 'alone',
    letter_5: ['alone', 'anole'],
    letter_4: [
      'aeon',
      'aloe',
      'elan',
      'enol',
      'lane',
      'lean',
      'leno',
      'loan',
      'lone',
      'noel',
      'olea',
    ],

    letter_3: ['ale', 'ane', 'eon', 'lea', 'nae', 'ole', 'one'],
  },
  {
    id: 3,
    word: 'aside',
    letter_5: ['aides', 'aside', 'ideas'],
    letter_4: [
      'aide',
      'aids',
      'dais',
      'desi',
      'dies',
      'idea',
      'ides',
      'sade',
      'sadi',
      'said',
      'side',
    ],
    letter_3: [
      'ads',
      'aid',
      'ais',
      'das',
      'die',
      'dis',
      'eds',
      'ids',
      'sad',
      'sae',
      'sea',
      'sei',
    ],
  },
];

export default {
  Words,
};
